
import React from 'react'
import type { Metadata } from "next";

type Album = {
  id : number,
  title:string
}

export const metadata: Metadata = {
  title: "Home Noureddine ",
  description: "Generated by create next app",
};


export default async function home() {
  const response = await fetch("https://jsonplaceholder.typicode.com/albums");
  if(!response.ok) throw new Error("Failed to fetch the data");
  
  const albums = await response.json();
  console.log("albums :",albums)


  return (
    <div>
      <h1>Home page</h1>
      <div className='grid grid-cols-3 gap-4'>
       {
        albums.map((album:Album)=>
        (
          <div
          key = {album.id}
          className='flex flex-col'
          >
            <h3>{album.title}</h3>
            <p>{album.id}</p>

          </div>
        ))
       }
      </div>
    </div>
  )
}
